spring:
  application:
    name: app-transation-api
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/transactions?allowPublicKeyRetrieval=true&useSSL=false
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:db/migration,classpath:db/testdata
management:
  datadog:
    metrics:
      export:
        api-key: ${DATADOG_API_KEY}
        application-key: ${DATADOG_APP_KEY}
        uri: ${DATADOG_URI}
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    baggage:
      correlation:
        enabled: true
        fields: [x-correlationID]
      remote-fields: [x-correlationID]
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  observations:
    key-values:
      my_custom_tag: ${spring.application.name}


