name: Java CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código-fonte
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configuração do JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # 3. Build do projeto
      - name: Build
        run: mvn clean install -Dskip.ut=true -Dskip.it=true

      # 4. Executar testes unitários
      - name: Run Unit Tests
        run: mvn test

      # 5. Executar testes de integração
      - name: Run Integration Tests
        run: mvn verify -Dskip.ut=true -Dskip.it=false
